// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeledocWebApplication.Core;

#nullable disable

namespace TeledocWebApplication.Migrations
{
    [DbContext(typeof(TeledocDbContext))]
    [Migration("20240728122324_1.1")]
    partial class _11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeledocWebApplication.Core.Model.Client", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("editDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("inn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("statusType")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("TeledocWebApplication.Core.Model.Founder", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("clientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("editDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("inn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("clientId");

                    b.ToTable("founders");
                });

            modelBuilder.Entity("TeledocWebApplication.Core.Model.Founder", b =>
                {
                    b.HasOne("TeledocWebApplication.Core.Model.Client", "client")
                        .WithMany("founders")
                        .HasForeignKey("clientId");

                    b.Navigation("client");
                });

            modelBuilder.Entity("TeledocWebApplication.Core.Model.Client", b =>
                {
                    b.Navigation("founders");
                });
#pragma warning restore 612, 618
        }
    }
}
